services:
  ar-simulation:
    image: ghcr.io/collaborativeroboticslab/algorithmic-robots-mars-surface:jazzy
    environment:
      - PYTHONUNBUFFERED=1                # GUI related
      - DISPLAY                           # GUI related
      - QT_X11_NO_MITSHM=1                # GUI related
      - NVIDIA_VISIBLE_DEVICES=all        # GUI related
      - NVIDIA_DRIVER_CAPABILITIES=all    # GUI related
      - ROS_DOMAIN_ID=${SIM_ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw    # GUI related    

  ar-workspace:
    image: ghcr.io/collaborativeroboticslab/turtlebot4-workspace:jazzy
    environment:
      - PYTHONUNBUFFERED=1                # GUI related
      - DISPLAY                           # GUI related
      - QT_X11_NO_MITSHM=1                # GUI related
      - NVIDIA_VISIBLE_DEVICES=all        # GUI related
      - NVIDIA_DRIVER_CAPABILITIES=all    # GUI related
      - ROS_DOMAIN_ID=${SIM_ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: host
    volumes:
      - ./workspace:/workspace:rw
      - ./code-server/config:/root/.config/code-server:rw
      - ./code-server/data:/root/.local/share/code-server:rw
      - /dev:/dev
